export default {
	p: { key: 'p' },
	pt: { key: 'pt' },
	pr: { key: 'pr' },
	pb: { key: 'pb' },
	pl: { key: 'pl' },
	px: { key: 'px' },
	py: { key: 'py' },
	m: { key: 'm' },
	mt: { key: 'mt' },
	mr: { key: 'mr' },
	mb: { key: 'mb' },
	ml: { key: 'ml' },
	mx: { key: 'mx' },
	my: { key: 'my' },
	spaceX: { key: "space-x" },
	spaceY: { key: "space-y" },
	negativeSpacing: { //TODO: Implement template literal types https://github.com/microsoft/TypeScript/pull/40336
			'-px': '1px',
			'-0': '0',
			'-1': '0.25rem',
			'-2': '0.5rem',
			'-3': '0.75rem',
			'-4': '1rem',
			'-5': '1.25rem',
			'-6': '1.5rem',
			'-8': '2rem',
			'-10': '2.5rem',
			'-12': '3rem',
			'-16': '4rem',
			'-20': '5rem',
			'-24': '6rem',
			'-32': '8rem',
			'-40': '10rem',
			'-48': '12rem',
			'-56': '14rem',
			'-64': '16rem',
		}
}